<?php

namespace Database\Seeders;

use App\Models\Review;
use Illuminate\Database\Seeder;

class ReviewSeeder extends Seeder
{
    public function run(): void
    {
        $reviews = [
            [
                'name' => 'Sarah & James Mitchell',
                'email' => 'sarah@example.com',
                'room_number' => 'Suite 3',
                'country' => 'United Kingdom',
                'stay_date' => '2026-03-15',
                'overall_rating' => 5,
                'cleanliness_rating' => 5,
                'comfort_rating' => 5,
                'service_rating' => 5,
                'location_rating' => 5,
                'value_rating' => 5,
                'review' => 'We cannot recommend The Garden Shed enough. Every detail has been thoughtfully considered, from the fresh flowers in the room to the homemade granola at breakfast. The garden views are stunning and the hosts could not have been more welcoming.',
                'suggestions' => null,
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-03-20 10:30:00',
            ],
            [
                'name' => 'Thomas Weber',
                'email' => 'thomas@example.com',
                'room_number' => 'Room 1',
                'country' => 'Germany',
                'stay_date' => '2026-02-28',
                'overall_rating' => 4,
                'cleanliness_rating' => 5,
                'comfort_rating' => 4,
                'service_rating' => 5,
                'location_rating' => 4,
                'value_rating' => 4,
                'review' => 'The Garden Shed is a beautiful place to disconnect and recharge. The room was clean and comfortable, the breakfast was delicious with local produce. The only small issue was that the Wi-Fi was a bit spotty in our room.',
                'suggestions' => 'A small fridge in the room would be nice for keeping water cool.',
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-03-05 14:00:00',
            ],
            [
                'name' => 'Emily Chen',
                'email' => 'emily@example.com',
                'room_number' => 'The Loft',
                'country' => 'Australia',
                'stay_date' => '2026-01-20',
                'overall_rating' => 5,
                'cleanliness_rating' => 5,
                'comfort_rating' => 5,
                'service_rating' => 4,
                'location_rating' => 5,
                'value_rating' => 5,
                'review' => 'Staying at The Garden Shed was the highlight of our South African trip. The loft room is beautifully appointed with high ceilings and skylights. Waking up to the sound of birds and the sight of the garden was magical.',
                'suggestions' => 'Would love to see an espresso machine in the room!',
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-01-25 09:15:00',
            ],
            [
                'name' => 'David & Anna Kowalski',
                'email' => 'david@example.com',
                'room_number' => 'Suite 1',
                'country' => 'Poland',
                'stay_date' => '2026-04-05',
                'overall_rating' => 5,
                'cleanliness_rating' => 5,
                'comfort_rating' => 5,
                'service_rating' => 5,
                'location_rating' => 5,
                'value_rating' => 5,
                'review' => 'From the moment we arrived we felt completely at home. The suite was spacious and luxurious, the garden is breathtaking, and the service is world-class. We have traveled extensively and this ranks among our favorite stays anywhere.',
                'suggestions' => null,
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-04-10 11:45:00',
            ],
            [
                'name' => 'Maria Santos',
                'email' => 'maria@example.com',
                'room_number' => 'Room 2',
                'country' => 'Philippines',
                'stay_date' => '2026-03-01',
                'overall_rating' => 4,
                'cleanliness_rating' => 4,
                'comfort_rating' => 4,
                'service_rating' => 5,
                'location_rating' => 4,
                'value_rating' => 4,
                'review' => 'The Garden Shed is a charming guesthouse with a peaceful atmosphere. The staff were incredibly friendly and helpful. The garden is beautiful and well-maintained. Breakfast was fresh and delicious every morning.',
                'suggestions' => 'A few more meal options for dinner would be appreciated.',
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-03-08 16:30:00',
            ],
            [
                'name' => 'Robert van Dijk',
                'email' => 'robert@example.com',
                'room_number' => 'Suite 2',
                'country' => 'Netherlands',
                'stay_date' => '2026-02-10',
                'overall_rating' => 3,
                'cleanliness_rating' => 4,
                'comfort_rating' => 3,
                'service_rating' => 4,
                'location_rating' => 3,
                'value_rating' => 3,
                'review' => 'The Garden Shed is lovely and the staff are wonderful. However, our room was a bit small for the price and the bed was not as comfortable as we had hoped. The breakfast was excellent and the garden is gorgeous.',
                'suggestions' => 'Upgrade the mattresses and consider adding more storage space in the rooms.',
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-02-15 08:00:00',
            ],
            [
                'name' => 'Claire & Michael O\'Brien',
                'email' => 'claire@example.com',
                'room_number' => 'The Loft',
                'country' => 'Ireland',
                'stay_date' => '2026-04-12',
                'overall_rating' => 5,
                'cleanliness_rating' => 5,
                'comfort_rating' => 5,
                'service_rating' => 5,
                'location_rating' => 4,
                'value_rating' => 5,
                'review' => 'We stumbled upon The Garden Shed while looking for a quiet weekend away and it was exactly what we needed. The loft is stunning, the hosts are incredibly warm, and the surroundings are beautiful. We will definitely be back.',
                'suggestions' => null,
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-04-16 13:20:00',
            ],
            [
                'name' => 'Yuki Tanaka',
                'email' => 'yuki@example.com',
                'room_number' => 'Room 3',
                'country' => 'Japan',
                'stay_date' => '2026-01-05',
                'overall_rating' => 5,
                'cleanliness_rating' => 5,
                'comfort_rating' => 5,
                'service_rating' => 5,
                'location_rating' => 5,
                'value_rating' => 5,
                'review' => 'The attention to detail at The Garden Shed is remarkable. Every aspect of our stay was thoughtfully curated, from the welcome tea to the handmade soaps in the bathroom. The hosts went above and beyond to make us feel special.',
                'suggestions' => null,
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-01-10 10:00:00',
            ],
            [
                'name' => 'Pieter Botha',
                'email' => 'pieter@example.com',
                'room_number' => 'Suite 1',
                'country' => 'South Africa',
                'stay_date' => '2026-03-25',
                'overall_rating' => 4,
                'cleanliness_rating' => 4,
                'comfort_rating' => 5,
                'service_rating' => 4,
                'location_rating' => 5,
                'value_rating' => 4,
                'review' => 'We booked The Garden Shed for a anniversary getaway and it was perfect. The suite was spacious and romantic, the garden was in full bloom, and the breakfast was incredible. Close enough to town but feels worlds away.',
                'suggestions' => 'A heated pool would make this place absolutely perfect.',
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-03-28 15:45:00',
            ],
            [
                'name' => 'Sophie Lambert',
                'email' => 'sophie@example.com',
                'room_number' => 'Room 1',
                'country' => 'France',
                'stay_date' => '2026-04-18',
                'overall_rating' => 5,
                'cleanliness_rating' => 5,
                'comfort_rating' => 5,
                'service_rating' => 5,
                'location_rating' => 5,
                'value_rating' => 5,
                'review' => 'The Garden Shed is a little piece of heaven in the South African countryside. The hosts are wonderful, the food is delicious, and the garden is a dream. We felt so welcomed and relaxed. Cannot wait to return.',
                'suggestions' => null,
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-04-22 12:10:00',
            ],
            [
                'name' => 'James Williamson',
                'email' => 'james@example.com',
                'room_number' => 'Room 2',
                'country' => 'Canada',
                'stay_date' => '2026-02-20',
                'overall_rating' => 4,
                'cleanliness_rating' => 4,
                'comfort_rating' => 4,
                'service_rating' => 5,
                'location_rating' => 4,
                'value_rating' => 4,
                'review' => 'My partner and I had a wonderful three nights at The Garden Shed. The room was cozy and clean, the garden views were beautiful, and the breakfast was delicious. The hosts shared great local tips for exploring the area.',
                'suggestions' => 'Some vegetarian dinner options would be nice.',
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-02-24 09:30:00',
            ],
            [
                'name' => 'Aisha Patel',
                'email' => 'aisha@example.com',
                'room_number' => 'The Loft',
                'country' => 'India',
                'stay_date' => '2026-01-28',
                'overall_rating' => 5,
                'cleanliness_rating' => 5,
                'comfort_rating' => 5,
                'service_rating' => 5,
                'location_rating' => 5,
                'value_rating' => 5,
                'review' => 'The Garden Shed exceeded every expectation. The loft room with its views over the garden was absolutely beautiful. The attention to detail, the warm hospitality, and the amazing breakfast made this a truly memorable stay.',
                'suggestions' => null,
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-02-01 11:00:00',
            ],
            [
                'name' => 'Carlos Mendez',
                'email' => 'carlos@example.com',
                'room_number' => 'Suite 3',
                'country' => 'Spain',
                'stay_date' => '2026-04-22',
                'overall_rating' => 4,
                'cleanliness_rating' => 5,
                'comfort_rating' => 4,
                'service_rating' => 4,
                'location_rating' => 4,
                'value_rating' => 4,
                'review' => 'We had a fantastic stay at The Garden Shed. The property is beautifully maintained with stunning gardens. The suite was spacious and tastefully decorated. The staff were attentive and friendly throughout our stay.',
                'suggestions' => 'A gym or fitness area would be a great addition.',
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-04-26 14:25:00',
            ],
            [
                'name' => 'Hannah & Mark Turner',
                'email' => 'hannah@example.com',
                'room_number' => 'Room 3',
                'country' => 'New Zealand',
                'stay_date' => '2026-03-10',
                'overall_rating' => 5,
                'cleanliness_rating' => 5,
                'comfort_rating' => 5,
                'service_rating' => 5,
                'location_rating' => 5,
                'value_rating' => 5,
                'review' => 'The Garden Shed has set the bar impossibly high for all future stays. Everything was perfect from start to finish. The room, the garden, the food, the hospitality - all world-class. We are already planning our return visit.',
                'suggestions' => null,
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-03-15 08:45:00',
            ],
            [
                'name' => 'Lars Johansson',
                'email' => 'lars@example.com',
                'room_number' => 'Suite 2',
                'country' => 'Sweden',
                'stay_date' => '2026-05-01',
                'overall_rating' => 4,
                'cleanliness_rating' => 5,
                'comfort_rating' => 4,
                'service_rating' => 4,
                'location_rating' => 4,
                'value_rating' => 3,
                'review' => 'The Garden Shed is undeniably beautiful and the service is excellent. Our suite was comfortable and well-appointed. The garden breakfast was a highlight. However, I felt the pricing was a bit high for what you get.',
                'suggestions' => 'Consider offering mid-week discounts or packages.',
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-05-05 16:00:00',
            ],
            [
                'name' => 'Nadia Petrova',
                'email' => 'nadia@example.com',
                'room_number' => 'Room 1',
                'country' => 'Russia',
                'stay_date' => '2026-05-10',
                'overall_rating' => 5,
                'cleanliness_rating' => 5,
                'comfort_rating' => 5,
                'service_rating' => 5,
                'location_rating' => 5,
                'value_rating' => 5,
                'review' => 'I came to The Garden Shed looking for peace and quiet and found so much more. The garden is a sanctuary, the room was beautiful and comfortable, and the hosts made me feel like family. A truly special place.',
                'suggestions' => null,
                'would_recommend' => true,
                'is_approved' => true,
                'created_at' => '2026-05-14 10:30:00',
            ],
            [
                'name' => 'Pending Guest',
                'email' => 'pending@example.com',
                'room_number' => 'Suite 1',
                'country' => 'United States',
                'stay_date' => '2026-05-20',
                'overall_rating' => 4,
                'cleanliness_rating' => 4,
                'comfort_rating' => 4,
                'service_rating' => 5,
                'location_rating' => 4,
                'value_rating' => 4,
                'review' => 'We had a wonderful time at The Garden Shed. The staff were amazing and the location is perfect for exploring the surrounding area. The room was comfortable and clean. Highly recommend for a relaxing getaway.',
                'suggestions' => 'More vegan options at breakfast would be great.',
                'would_recommend' => true,
                'is_approved' => false,
                'created_at' => '2026-05-22 09:00:00',
            ],
            [
                'name' => 'Review Pending',
                'email' => 'test@example.com',
                'room_number' => 'Room 2',
                'country' => 'Italy',
                'stay_date' => '2026-05-25',
                'overall_rating' => 3,
                'cleanliness_rating' => 3,
                'comfort_rating' => 3,
                'service_rating' => 4,
                'location_rating' => 4,
                'value_rating' => 3,
                'review' => 'The Garden Shed is a nice property but our experience was mixed. The room was decent but had some maintenance issues. The garden and common areas are beautiful. Staff were friendly and helpful.',
                'suggestions' => 'Please address the maintenance issues in Room 2 - the bathroom sink was leaking.',
                'would_recommend' => false,
                'is_approved' => false,
                'created_at' => '2026-05-28 14:15:00',
            ],
        ];

        foreach ($reviews as $review) {
            Review::create($review);
        }
    }
}
